### ISSUE TITLE
Traceback Error While Importing Koohii Progression Anki Version 2.1.35 

### ISSUE THREAD

**Issue by maebutart** [Mauville/Koohii2Anki#14]
Similarly to someone elses issue, I get greeted with a Traceback Error while trying to import my Koohii progression. Unlike them, I don't know how to fix it. 

![Traceback Error](https://user-images.githubusercontent.com/75088408/100375977-4f017580-2fd4-11eb-9df7-92b69b6b51f2.PNG)

Any help would be appreciated

**Comment by ur-miri** [comment]
Duplicate of #14

**Comment by Mauville** [comment]
Solved on #13
