### ISSUE TITLE
Does not use my_stories.csv when running Python script (approach for Macs)

### ISSUE THREAD

**Issue by zzzbra** [Mauville/Koohii2Anki#16]
Following all the steps in the README does not generate the cards with the stories that a user has selected from their kanji.koohii.com days of use. This is probably an issue with the python script. Not having a Windows machine, I am unable to verify by running the .exe file.

**Comment by Mauville** [comment]
Could you share a bit more details into what happens? Does the script not output anything altogether? Have you granted file access permissions to Python on Macos?

**Comment by Mauville** [comment]
Closing because inactive
