### ISSUE TITLE
Move _jquery-3.4.1.min.js into your collection.media directory Issue

### ISSUE THREAD

**Issue by joseph-allen** [Mauville/Koohii2Anki#17]
The documentation seems to have moved from the previously linked page.

[Here](https://docs.ankiweb.net/files.html) is the new section for this. I also found this didn't work for my version of Anki.

If you are on Mac and can't find it from there, you can find where Anki is installed from Ankis built-in Addons menu

Tools > Add-ons > Open add-ons folder (or view files)

you will be taken to the add-ons folder. If you navigate up a folder (Cmd-UP) you should see a folder with you username on it. Inside that you should see the collection.media folder.

**Comment by Mauville** [comment]
I've incorporated the newer links to the documentation. Thank you for the feedback!
